spring.application.name=dsa-hint-backend
server.port=8080
gemini.api.url=https://generativelanguage.googleapis.com/v1beta
gemini.model=gemini-2.5-flash-lite
gemini.api.key=AIzaSyB0YU2MY7Kj-jkE2Z8F56qURPeEdZJNytQ
c